[build]
  command = "npm run build:netlify"
  publish = "."

[build.environment]
  NODE_VERSION = "18"

# Redirect all 404s to index.html for SPA support
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 